#!/usr/bin/env python3
"""
Main Executable
"""

import typer
import moreorless


app = typer.Typer()
SCOREBOARD_PATH = "scoreboard.json"


@app.command()
def more_or_less_game():
    """
    More or less Game
    """
    moreorless.game(scoreboard_path=SCOREBOARD_PATH)


if __name__ == "__main__":
    app()
