#!/usr/bin/env python3
"""
Main Executable
"""

import pathlib
import typer
import moreorless

app = typer.Typer()
SCOREBOARD_PATH = "scoreboard.json"


@app.command()
def scoreboard(scoreboard_path: pathlib.Path = SCOREBOARD_PATH):
    """
    More or less Scoreboard
    """
    moreorless.game_scoreboard(scoreboard_path=scoreboard_path)


@app.command()
def more_or_less_game(scoreboard_path: pathlib.Path = SCOREBOARD_PATH):
    """
    More or less Game
    """
    moreorless.game(scoreboard_path=scoreboard_path)


if __name__ == "__main__":
    try:
        app()
    except SystemExit:
        pass
